export enum ComponentName {
  Button = `Button`,
  ChangePasswordForm = `ChangePasswordForm`,
  ChatAside = `ChatAside`,
  ChatItem = `ChatItem`,
  ChatList = `ChatList`,
  ErrorMessage = `ErrorMessage`,
  InputItem = `InputItem`,
  InputItemControlled = `InputItemControlled`,
  LinkBack = `LinkBack`,
  Messages = `Messages`,
  MessagesClip = `MessagesClip`,
  MessagesControls = `MessagesControls`,
  MessagesEmpty = `MessagesEmpty`,
  MessagesItem = `MessagesItem`,
  MessagesList = `MessagesList`,
  MessagesSend = `MessagesSend`,
  ProfileControls = `ProfileControls`,
  ProfileForm = `ProfileForm`,
  Search = `Search`,
  SearchBar = `SearchBar`,
  User = `User`,
  ChangePassword = `ChangePassword`,
  Chats = `Chats`,
  Login = `Login`,
  Profile = `Profile`,
  Register = `Register`,
}
